default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      name: black
      language_version: python3.9
      entry: black
      types: [ python ]
      args: [ --line-length=120, --skip-string-normalization]

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language_version: python3.9
        types: [python]
