version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Support_test/dev.env
    ports:
      - "5432:5432"

  redis:
    image: redis

  django:
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  Support_test:
  redis:
